import hubs from '@/content/seo-drafts/hubs.json';
import ContentDiscovery from './ContentDiscovery';
import {HelpHeader,HelpFooter} from './HelpChrome';
import HelpCenterSearch from './HelpCenterSearch';
import help from '@/content/seo-drafts/help.json';
export default function HelpCenter(){
 const h=hubs.find(h=>h.key==='help')!;
 const startingPoints=['Store setup','Products','Orders'].map(category=>help.find(a=>a.category===category)!);
 return <div className="hc-shell"><HelpHeader/><main id="main" className="hc-home"><div className="hc-home-breadcrumb"><ContentDiscovery route={h.route} title={h.title} description={h.description} kind="CollectionPage"/></div><section className="hc-welcome"><div className="hc-hero"><p className="hc-eyebrow">THE oBizee FIELD GUIDE</p><h1>{h.title}</h1><p className="hc-welcome-copy">A little clarity. Your next step.<br/>Get back to the business you love.</p><p className="hc-coverage">{h.description}</p><a className="hc-explore" href="#help-query">Find an answer ↓</a></div><aside className="hc-start"><span className="hc-start-note">ONE THING AT A TIME</span><h2>Where are you<br/>starting today?</h2><ol>{startingPoints.map((a,i)=><li key={a.key}><a href={a.route}><span className="hc-task-number">0{i+1}</span><span><small>{a.category}</small><strong>{a.title}</strong></span><span aria-hidden="true">↗</span></a></li>)}</ol><p>No jargon hunt. Pick a task, follow the steps.</p></aside></section><div className="hc-directory-heading"><p className="hc-eyebrow">YOUR HELP LIBRARY</p><h2>Less searching. More doing.</h2></div><HelpCenterSearch/><aside className="hc-source-note"><h2>Clear steps, with a clear verification boundary</h2><p>These guides were checked against local V1 application source on 26 September 2026, not independently executed in a live account. Your deployed version may differ. Check saved orders, stock and payment records before repeating an action.</p><p>Never share passwords, OTPs, payment PINs or secret keys with support.</p></aside></main><HelpFooter/></div>;
}
